<a href="https://colab.research.google.com/github/adriaaaann/readingQuota/blob/main/Reading_Quota.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder


In [ ]:
dataset = pd.read_csv('/content/Read_Span.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print (X)

[[25  2  3  4  4  4 20]
 [35  3  4  5  5  4 30]
 [40  4  2  3  3  3 15]
 [30  2  3  4  4  4 25]
 [45  4  5  5  5  5 35]
 [28  3  4  4  4  4 22]
 [38  4  3  5  4  5 28]
 [50  5  5  5  5  5 40]
 [33  2  1  3  2  2 18]
 [42  5  4  5  5  5 32]
 [22  2  2  2  2  2 10]
 [32  2  3  2  2  2 12]
 [48  5  5  5  5  5 45]
 [26  2  2  2  2  2 14]
 [37  4  4  5  5  5 30]
 [14  1  2  2  2  2  5]
 [18  1  2  2  2  2  8]
 [12  1  1  1  1  1  1]
 [16  1  2  2  1  2  4]
 [20  1  2  2  2  2  7]
 [ 9  1  1  1  2  1  1]
 [36  3  5  4  1  4 26]
 [29  3  4  3  5  3 23]]


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
from sklearn.linear_model import LinearRegression

regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [ ]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision = 2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[11.41 14.  ]
 [11.16 12.  ]
 [14.02 20.  ]
 [22.02 17.  ]
 [ 7.86  4.  ]]


In [ ]:
new_input = np.array([[45, 5, 5, 5, 5, 5, 34]])
prediction = regressor.predict(new_input)
prediction = np.round(prediction).astype(int)
print(f'Predicted Reading Span for New Input: {prediction} minutes per session')

Predicted Reading Span for New Input: [23] minutes per session
